POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email":"byron.fields@reqres.in",
    "first_name":"Byron",
    "last_name":"Fields",
    "avatar":"https://reqres.in/img/faces/10-image.jpg"
}

###

GET http://localhost:3000/api/user/1

###

GET http://localhost:3000/api/user/649c21791a197db0cebabd66/avatar
